### ISSUE TITLE
Use ShellCheck for CI

### ISSUE THREAD

**Issue by devnote-dev** [teamblueprint/main#11]
Having [ShellCheck](https://github.com/koalaman/shellcheck) for the CI workflow would be useful for catching bugs caused by shell edge-cases and enforcing safe practices. You can view its extensive list [in the wiki](https://www.shellcheck.net/wiki/). There are over 100 issues in `blueprint.sh` at present.

**Comment by prplwtf** [comment]
Thank you for the suggestion, I've install shellcheck and it appears that there are indeed a lot of problems with `blueprint.sh`.

I'll be slowly going over these when I have the time to do so. I'll leave this issue open until most (if not all) issues are resolved.

**Comment by prplwtf** [comment]
I'll re-add this issue to the "Framework Progress Board" as I'm trying to have a better overview of current issues/bugs/to-do-things.

**Comment by prplwtf** [comment]
@devnote-dev I've gone through every single advisory on `blueprint.sh` and added a `.shellcheckrc` file for the issues that cannot be fixed due to file/code structure regarding the development file tree.

I might need to go through a few of Blueprint's libraries in the coming days, hence why I'm keeping this Issue open for now.

[*thank you shellcheck vscode extension for making my life easier*](https://open-vsx.org/extension/timonwong/shellcheck)

**Comment by prplwtf** [comment]
@devnote-dev There we go, I've now gone through (and tested) **all of Blueprint's shell libraries** with ShellCheck, which means, this issue can now *finally* be closed.
