### ISSUE TITLE
Weak Hardware

### ISSUE THREAD

**Issue by Phedona** [teamblueprint/main#4]
Hi! Regarding an email I sent, I'm now creating the issue. On my hardware, it's not possible for me to install Blueprint and a theme that requires it, as my server seems to be too weak. I have 512mb of RAM and a 1vcore processor, which appears to be insufficient. For those who have managed to install it: What resources do you have available? How powerful are your servers? What should I keep in mind?

**Comment by BlueTree242** [comment]
Running pterodactyl on 512mb ram is a terrible idea, it's already insufficient

**Comment by Ahwxorg** [comment]
Hello! The base OS usually already requires about half of your specifications. You should not try to run Blueprint or any game servers on your machine, since it does not have the capabilities to virtualise pretty much anything useful regarding game servers, and since you're running Pterodactyl, that's what you need.
